version: '3'
services:
  mongodb:
    image: mongo
    container_name: synapsis-backend-test
    environment:
      - MONGODB_URI=${MONGODB_URI}

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_NAME=${MONGODB_NAME}
    ports:
      - ${PORT}:9000
    container_name: service-synapsis-backend-test